import React,{useEffect,useState} from 'react'
import {Plus,Search} from 'lucide-react'
import {api} from '../lib/api'
import {Empty,Field,Loader,Modal,PageHeader} from '../components/UI'
const blank={name:'',email:'',phone:'',company:'',notes:'',tags:''}
export default function Customers(){
 const [items,setItems]=useState([]),[q,setQ]=useState(''),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[f,setF]=useState(blank),[err,setErr]=useState('')
 const load=()=>{setLoading(true);api(`/customers/?search=${encodeURIComponent(q)}`).then(d=>setItems(d.results||d)).catch(e=>setErr(e.message)).finally(()=>setLoading(false))};useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[q])
 const save=async e=>{e.preventDefault();try{await api('/customers/',{method:'POST',body:JSON.stringify({...f,tags:f.tags.split(',').map(x=>x.trim()).filter(Boolean)})});setOpen(false);setF(blank);load()}catch(e){setErr(e.message)}}
 return <><PageHeader title="Customers" subtitle="Customer directory and support history." action={<button className="btn primary" onClick={()=>setOpen(true)}><Plus size={17}/>Add customer</button>}/>{err&&<div className="error-box">{err}</div>}<div className="toolbar"><div className="searchbox"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name, email, phone, company..."/></div></div><section className="panel no-pad">{loading?<Loader/>:items.length===0?<Empty/>:<div className="table-wrap"><table><thead><tr><th>Customer</th><th>Company</th><th>Phone</th><th>Tickets</th><th>Tags</th><th>Added</th></tr></thead><tbody>{items.map(c=><tr key={c.id}><td><strong>{c.name}</strong><small>{c.email}</small></td><td>{c.company||'—'}</td><td>{c.phone||'—'}</td><td><strong>{c.ticket_count}</strong></td><td><div className="tag-list">{(c.tags||[]).map(x=><span className="tag" key={x}>{x}</span>)}</div></td><td>{new Date(c.created_at).toLocaleDateString()}</td></tr>)}</tbody></table></div>}</section><Modal open={open} onClose={()=>setOpen(false)} title="Add customer"><form className="form-grid" onSubmit={save}><Field label="Full name"><input required value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></Field><Field label="Email"><input type="email" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/></Field><Field label="Phone"><input value={f.phone} onChange={e=>setF({...f,phone:e.target.value})}/></Field><Field label="Company"><input value={f.company} onChange={e=>setF({...f,company:e.target.value})}/></Field><Field label="Tags"><input value={f.tags} onChange={e=>setF({...f,tags:e.target.value})} placeholder="vip, enterprise"/></Field><Field label="Notes"><textarea rows="4" value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></Field><div className="form-actions"><button type="button" className="btn" onClick={()=>setOpen(false)}>Cancel</button><button className="btn primary">Save customer</button></div></form></Modal></>
}
