import React,{useEffect,useState} from 'react'
import {BookOpen,Plus,Search} from 'lucide-react'
import {api} from '../lib/api'
import {Empty,Field,Loader,Modal,PageHeader} from '../components/UI'
const blank={title:'',category:'',content:'',is_published:true}
export default function Knowledge(){
 const [items,setItems]=useState([]),[q,setQ]=useState(''),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[f,setF]=useState(blank),[selected,setSelected]=useState(null),[err,setErr]=useState('')
 const load=()=>{setLoading(true);api(`/knowledge/?search=${encodeURIComponent(q)}`).then(d=>setItems(d.results||d)).catch(e=>setErr(e.message)).finally(()=>setLoading(false))};useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[q])
 const save=async e=>{e.preventDefault();try{await api('/knowledge/',{method:'POST',body:JSON.stringify(f)});setOpen(false);setF(blank);load()}catch(e){setErr(e.message)}}
 return <><PageHeader title="Knowledge Base" subtitle="Reusable support guidance that also grounds AI reply suggestions." action={<button className="btn primary" onClick={()=>setOpen(true)}><Plus size={17}/>New article</button>}/>{err&&<div className="error-box">{err}</div>}<div className="toolbar"><div className="searchbox"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search articles..."/></div></div>{loading?<Loader/>:items.length===0?<Empty title="No knowledge articles"/>:<div className="kb-grid">{items.map(a=><button key={a.id} className="kb-card" onClick={()=>setSelected(a)}><div className="kb-icon"><BookOpen size={20}/></div><div><span>{a.category||'General'}</span><h3>{a.title}</h3><p>{a.content.slice(0,170)}{a.content.length>170?'…':''}</p><small>Updated {new Date(a.updated_at).toLocaleDateString()}</small></div></button>)}</div>}<Modal open={open} onClose={()=>setOpen(false)} title="Create knowledge article" wide><form className="form-grid" onSubmit={save}><Field label="Title"><input required value={f.title} onChange={e=>setF({...f,title:e.target.value})}/></Field><Field label="Category"><input value={f.category} onChange={e=>setF({...f,category:e.target.value})}/></Field><Field label="Article content"><textarea required rows="12" value={f.content} onChange={e=>setF({...f,content:e.target.value})}/></Field><label className="check"><input type="checkbox" checked={f.is_published} onChange={e=>setF({...f,is_published:e.target.checked})}/>Published and available to agents/AI</label><div className="form-actions"><button type="button" className="btn" onClick={()=>setOpen(false)}>Cancel</button><button className="btn primary">Publish article</button></div></form></Modal><Modal open={!!selected} onClose={()=>setSelected(null)} title={selected?.title||''} wide>{selected&&<article className="article-view"><div className="article-meta">{selected.category||'General'} · {selected.is_published?'Published':'Draft'} · by {selected.created_by||'Unknown'}</div><p>{selected.content}</p></article>}</Modal></>
}
