import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name='Customer', fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('name',models.CharField(max_length=160)),('email',models.EmailField(blank=True,max_length=254)),('phone',models.CharField(blank=True,max_length=40)),('company',models.CharField(blank=True,max_length=160)),('notes',models.TextField(blank=True)),('tags',models.JSONField(blank=True,default=list)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True))], options={'ordering':['-created_at']}),
        migrations.CreateModel(name='AgentProfile', fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('role',models.CharField(choices=[('admin','Admin'),('supervisor','Supervisor'),('agent','Agent')],default='agent',max_length=20)),('display_name',models.CharField(blank=True,max_length=120)),('created_at',models.DateTimeField(auto_now_add=True)),('user',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='agent_profile',to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='KnowledgeBaseArticle', fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('title',models.CharField(max_length=220)),('slug',models.SlugField(max_length=240,unique=True)),('category',models.CharField(blank=True,max_length=100)),('content',models.TextField()),('is_published',models.BooleanField(default=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL))], options={'ordering':['-updated_at']}),
        migrations.CreateModel(name='Ticket', fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('ticket_number',models.CharField(editable=False,max_length=32,unique=True)),('subject',models.CharField(max_length=220)),('description',models.TextField()),('status',models.CharField(choices=[('open','Open'),('pending','Pending'),('resolved','Resolved'),('closed','Closed')],default='open',max_length=20)),('priority',models.CharField(choices=[('low','Low'),('medium','Medium'),('high','High'),('urgent','Urgent')],default='medium',max_length=20)),('source',models.CharField(choices=[('email','Email'),('web','Web'),('phone','Phone'),('chat','Chat'),('social','Social')],default='web',max_length=20)),('category',models.CharField(blank=True,max_length=100)),('tags',models.JSONField(blank=True,default=list)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('first_response_at',models.DateTimeField(blank=True,null=True)),('resolved_at',models.DateTimeField(blank=True,null=True)),('assigned_to',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='assigned_tickets',to=settings.AUTH_USER_MODEL)),('customer',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='tickets',to='support.customer'))], options={'ordering':['-updated_at']}),
        migrations.CreateModel(name='TicketMessage', fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('author_name',models.CharField(blank=True,max_length=160)),('body',models.TextField()),('is_internal',models.BooleanField(default=False)),('is_ai_generated',models.BooleanField(default=False)),('created_at',models.DateTimeField(auto_now_add=True)),('author',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='ticket_messages',to=settings.AUTH_USER_MODEL)),('ticket',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='messages',to='support.ticket'))], options={'ordering':['created_at']}),
        migrations.CreateModel(name='ActivityLog', fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('action',models.CharField(max_length=120)),('entity_type',models.CharField(max_length=80)),('entity_id',models.CharField(blank=True,max_length=120)),('summary',models.CharField(max_length=280)),('metadata',models.JSONField(blank=True,default=dict)),('created_at',models.DateTimeField(auto_now_add=True)),('actor',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL))], options={'ordering':['-created_at']}),
    ]
